-- MySQL Script generated by MySQL Workbench
-- Thu Apr  6 18:55:12 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema board222
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema board
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `board` ;

-- -----------------------------------------------------
-- Schema board
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `board` DEFAULT CHARACTER SET utf8 ;
USE `board` ;

-- -----------------------------------------------------
-- Table `board`.`SPRING_SESSION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `board`.`SPRING_SESSION` ;

CREATE TABLE IF NOT EXISTS `board`.`SPRING_SESSION` (
  `SESSION_ID` CHAR(36) NOT NULL,
  `CREATION_TIME` BIGINT(20) NOT NULL,
  `LAST_ACCESS_TIME` BIGINT(20) NOT NULL,
  `MAX_INACTIVE_INTERVAL` INT(11) NOT NULL,
  `PRINCIPAL_NAME` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`SESSION_ID`),
  INDEX `SPRING_SESSION_IX1` (`LAST_ACCESS_TIME` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `board`.`SPRING_SESSION_ATTRIBUTES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `board`.`SPRING_SESSION_ATTRIBUTES` ;

CREATE TABLE IF NOT EXISTS `board`.`SPRING_SESSION_ATTRIBUTES` (
  `SESSION_ID` CHAR(36) NOT NULL,
  `ATTRIBUTE_NAME` VARCHAR(200) NOT NULL,
  `ATTRIBUTE_BYTES` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`SESSION_ID`, `ATTRIBUTE_NAME`),
  INDEX `SPRING_SESSION_ATTRIBUTES_IX1` (`SESSION_ID` ASC),
  CONSTRAINT `SPRING_SESSION_ATTRIBUTES_FK`
    FOREIGN KEY (`SESSION_ID`)
    REFERENCES `board`.`SPRING_SESSION` (`SESSION_ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `board`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `board`.`comments` ;

CREATE TABLE IF NOT EXISTS `board`.`comments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `post_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `board`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `board`.`posts` ;

CREATE TABLE IF NOT EXISTS `board`.`posts` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `type` VARCHAR(5) NOT NULL,
  `content` TEXT NOT NULL,
  `view_count` BIGINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `board`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `board`.`users` ;

CREATE TABLE IF NOT EXISTS `board`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(12) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `profile_img` VARCHAR(100) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 73
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `board`.`user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `board`.`user_roles` ;

CREATE TABLE IF NOT EXISTS `board`.`user_roles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
